{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.0.2"
    }
  },
  "component" : {
    "group" : "com.github.CanHub",
    "module" : "Android-Image-Cropper",
    "version" : "4.1.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "androidx.databinding",
      "module" : "viewbinding",
      "version" : {
        "requires" : "7.0.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.5.20"
      }
    } ],
    "files" : [ {
      "name" : "Android-Image-Cropper-4.1.0.aar",
      "url" : "Android-Image-Cropper-4.1.0.aar",
      "size" : 194682,
      "sha512" : "67d0fb841d5af278bbaf5fe07a3b7b94b5834fc9d3538d297bc280c49d86b20b14661440a0467cd7108dd38d824ca2d4f730444255b442f7b42093a0f2747d8b",
      "sha256" : "4be5d6344c793961de35137cae81d22995540055e5e025ea74df77ca3095089b",
      "sha1" : "be1657bd50d927802ca6450579c2d30bf0aacb3f",
      "md5" : "cde5a7457c4a91a00806d1d51c458b00"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-parcelize-runtime",
      "version" : {
        "requires" : "1.5.20"
      }
    }, {
      "group" : "androidx.databinding",
      "module" : "viewbinding",
      "version" : {
        "requires" : "7.0.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.5.20"
      }
    }, {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.3.1"
      }
    }, {
      "group" : "androidx.activity",
      "module" : "activity-ktx",
      "version" : {
        "requires" : "1.3.1"
      }
    }, {
      "group" : "androidx.exifinterface",
      "module" : "exifinterface",
      "version" : {
        "requires" : "1.3.3"
      }
    }, {
      "group" : "androidx.core",
      "module" : "core-ktx",
      "version" : {
        "requires" : "1.6.0"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.5.1"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-android",
      "version" : {
        "requires" : "1.5.1"
      }
    } ],
    "files" : [ {
      "name" : "Android-Image-Cropper-4.1.0.aar",
      "url" : "Android-Image-Cropper-4.1.0.aar",
      "size" : 194682,
      "sha512" : "67d0fb841d5af278bbaf5fe07a3b7b94b5834fc9d3538d297bc280c49d86b20b14661440a0467cd7108dd38d824ca2d4f730444255b442f7b42093a0f2747d8b",
      "sha256" : "4be5d6344c793961de35137cae81d22995540055e5e025ea74df77ca3095089b",
      "sha1" : "be1657bd50d927802ca6450579c2d30bf0aacb3f",
      "md5" : "cde5a7457c4a91a00806d1d51c458b00"
    } ]
  } ]
}